image:
  file: .gitpod.dockerfile
ports:
  - port: 8000
    onOpen: ignore
  - port: 8001
    onOpen: ignore
  - port: 3306
    onOpen: ignore
tasks:
  - name: Laravel
    init: composer install
    command: >
        cp .env.example .env;
        php artisan key:generate;
        php artisan serve;
  - name: MySQL
    command: >
        mysqld
  - name: Apache
    command: >
        apachectl start;
        multitail /var/log/apache2/error.log -I /var/log/apache2/access.log
